export const FACETURN_CONSTANTS = {
	MAX_DECK_SIZE: 24,
	CREW_SLOTS: 2,
	MOVES_PER_DECK: 20,
	OPENING_HAND_SIZE: 3,
	HAND_LIMIT: 7,

	DRAFTING_DURATION_MS: 5 * 60 * 1_000,
	RPS_DURATION_MS: 30 * 1_000,
	MULLIGAN_DURATION_MS: 30 * 1_000,
	ACTIVE_TURN_DURATION_MS: 35 * 1_000,
	CHALLENGE_WINDOW_MS: 15 * 1_000,
	MOVE_CHAIN_WINDOW_MS: 15 * 1_000,
	DEFEND_DECLARED_MS: 15 * 1_000,
	DEFEND_WINDOW_MS: 15 * 1_000,
	DEFEND_CHALLENGE_MS: 15 * 1_000,
	RESOLUTION_DISPLAY_MS: 3 * 1_000,

	STRIKE_CASH_COST: 3,
	DEFEND_CASH_COST: 0,
	COLLECT_CASH_COST: 0,
	UNTURN_CASH_COST: 4,

	BOSS_FACE_TURN_COST: 6,

	COLLECT_CASH_GAIN: 2,

	PASSIVE_CASH_CAP: 10,

	BOSS_DEFAULT_HP: 100,
	MAX_ACTIVE_MOVE_SLOTS: 3,

	ROUND_LIMIT_DUEL: 15,
	ROUND_LIMIT_TEAMS: 18,
	ROUND_LIMIT_FFA: 20,

	TEAM_SIZE: 3,
	FFA_MIN_PLAYERS: 3,
	FFA_MAX_PLAYERS: 6,
} as const;

export function getFaceturnSeatBounds(
	mode: "duel" | "ffa" | "teams",
): { min: number; max: number } {
	if (mode === "duel") return { min: 2, max: 2 };
	if (mode === "teams") {
		return { min: 3, max: FACETURN_CONSTANTS.TEAM_SIZE * 2 };
	}
	return {
		min: FACETURN_CONSTANTS.FFA_MIN_PLAYERS,
		max: FACETURN_CONSTANTS.FFA_MAX_PLAYERS,
	};
}